### ISSUE TITLE
Does this project still alive?

### ISSUE THREAD

**Issue by SilverRainZ** [Snaipe/python-rst2ansi#13]
Thank  for this awesome project.

It seems does't works on the latest python, what the future plan of this project?

**Comment by mlech-reef** [comment]
Hi!

What is the problem? I have tested it on 3.10 and it seems to work fine.

Best Regards

**Comment by SilverRainZ** [comment]
Hello, I got this error:

```
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rst2ansi
>>> from rst2ansi import rst2ansi
>>> print(rst2ansi('I **love** reStructuredText!'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/la/.local/lib/python3.9/site-packages/rst2ansi/__init__.py", line 48, in rst2ansi
    out = core.publish_string(input_string.decode('utf-8'), settings_overrides=overrides, writer=Writer(unicode=output_encoding.startswith('utf')))
AttributeError: 'str' object has no attribute 'decode'
>>> 
```

**Comment by mlech-reef** [comment]
The example is for Python 2 with `from __future__ import print` included.

This is for 3:

```python
from rst2ansi import rst2ansi

print(rst2ansi('I **love** reStructuredText!'.encode()))
```

**Comment by Snaipe** [comment]
That arguably sounds like a regression, this lib was made with python 3 in mind. I think the backward-compatibility commit introduce this bug.
